<a href="https://colab.research.google.com/github/Kanyarat-S/DWDM21/blob/main/Distance_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np # package สำหรับทำงานกับ ข้อูลที่เป็นตัวเลข {อยู่ในรูปแบบ matrix}

## Numpy Array

สร้าง Numpy Array

In [3]:
np_a = np.array([[1,2,3],[4,5,6]]) #สร้าง numpy array ที่มี 2 แถว 3 หลัก

In [4]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
np_a.shape

(2, 3)

In [6]:
np_b = np.array([[1,4],[2,5],[3,6]])
np_b

array([[1, 4],
       [2, 5],
       [3, 6]])

### matrix transpose

In [7]:
np_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

### สร้าง matrix เริ่มต้น (zeros, ones)

In [8]:
np_z = np.zeros((4,5))
np_z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np_o = np.ones((5,6))
np_o

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [10]:
np_200 = 200 * np.ones((4,7)) #อยากได้ค่า matrix 200 ถ้าอยากได้ค่าไหนให้เอาค่านั้นมาคูณ
np_200

array([[200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.]])

### สร้าง matrix random

In [11]:
np.random.rand(5,5) #random เลขมาจาก normal distribution ที่มี mu = 0 std = 1

array([[0.05082801, 0.34448351, 0.74618865, 0.84351681, 0.400677  ],
       [0.83967215, 0.85235598, 0.91740999, 0.02372842, 0.18080406],
       [0.45243677, 0.92544144, 0.50114641, 0.55678671, 0.67991482],
       [0.99601647, 0.36984585, 0.92556748, 0.92915502, 0.39070426],
       [0.96561375, 0.89420207, 0.49603778, 0.84966708, 0.8055756 ]])

In [12]:
2+(5*np.random.rand(3,3)) #random เลขมาจาก normal distribution ที่มี mu = 2 std = 5

array([[6.12036909, 5.01249555, 3.23847331],
       [3.87057734, 4.59523995, 6.23957321],
       [6.85312721, 4.95317021, 2.64246698]])

In [13]:
np.random.randint(5,11,(4,5)) #random เลขจำนวนเต็มระหว่าง (5,11) ขนาด (4x5)

array([[10,  6, 10, 10,  6],
       [ 7,  7,  8,  9,  5],
       [ 7,  5,  7, 10,  6],
       [ 9,  8,  7,  8,  8]])